FROM ubuntu:latest AS base

ARG TARGETARCH

# Install common utils
RUN apt-get -y update && \
    apt-get -y install zip gzip xz-utils curl wget rsync openssl gpg cron ca-certificates lsb-release

# Install rclone
RUN curl -sSL https://downloads.rclone.org/rclone-current-linux-$TARGETARCH.zip -o rclone.zip && \
    unzip rclone.zip && \
    install -Dm755 rclone-*-linux-$TARGETARCH/rclone /usr/bin/rclone && \
    rm -rf rclone.zip rclone-*-linux-$TARGETARCH
